import Foundation

/// A stable logical key for a generated cache artifact.
///
/// A cache entry is identified by this key plus the codec identifier. Include
/// every input that can change the generated bytes in `identity`, `variants`,
/// or `versions`.
public struct CacheKey: Sendable, Hashable, Codable {
    /// A logical partition for related artifacts inside one shared cache.
    public var namespace: String
    /// The stable identity of the source item or generated artifact.
    public var identity: String
    /// Inputs that distinguish alternate generated forms for the same item.
    public var variants: [CacheKeyComponent]
    /// Explicit invalidation inputs, such as renderer or source-data versions.
    public var versions: [CacheKeyComponent]

    /// Creates a cache key from a namespace, identity, variants, and versions.
    public init(
        namespace: String,
        identity: String,
        variants: [CacheKeyComponent] = [],
        versions: [CacheKeyComponent] = []
    ) {
        self.namespace = namespace
        self.identity = identity
        self.variants = variants
        self.versions = versions
    }

    /// Creates a cache key in the supplied namespace.
    public init(_ identity: String, namespace: String = "default") {
        self.init(namespace: namespace, identity: identity)
    }

    /// Returns a copy of the key with an additional variant component.
    public func variant<Value: CustomStringConvertible & Sendable>(
        _ name: String,
        _ value: Value
    ) -> CacheKey {
        var key = self
        key.variants.append(CacheKeyComponent(name: name, value: String(describing: value)))
        return key
    }

    /// Returns a copy of the key with an additional version component.
    public func version<Value: CustomStringConvertible & Sendable>(
        _ name: String,
        _ value: Value
    ) -> CacheKey {
        var key = self
        key.versions.append(CacheKeyComponent(name: name, value: String(describing: value)))
        return key
    }
}

extension CacheKey {
    /// A stable, key-only identifier derived from this key's canonical form.
    ///
    /// Use this when code outside Yashima needs an opaque string that stays the
    /// same across process launches for the same `CacheKey`, such as log labels
    /// or auxiliary file names. This is not a cache entry identifier: stored
    /// entries are identified by both `CacheKey` and `CacheCodec.identifier`.
    public var stableIdentifier: String {
        stableHash.rawValue
    }

    public static func == (lhs: CacheKey, rhs: CacheKey) -> Bool {
        lhs.canonicalRepresentation == rhs.canonicalRepresentation
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(stableHash.rawValue)
    }
}

/// A named value used in a `CacheKey`.
public struct CacheKeyComponent: Sendable, Hashable, Codable {
    /// The component name.
    public var name: String
    /// The component value, already normalized to a stable string.
    public var value: String

    /// Creates a named key component.
    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }

    /// Creates a named key component.
    public init(_ name: String, _ value: String) {
        self.init(name: name, value: value)
    }
}

extension CacheKey {
    var canonicalRepresentation: Data {
        var writer = CacheCanonicalWriter()
        writer.appendString("yashima.cache-key.v1")
        writer.appendString("namespace")
        writer.appendString(namespace)
        writer.appendString("identity")
        writer.appendString(identity)
        writer.appendString("variants")
        writer.appendString(String(variants.count))
        for component in variants.canonicalSorted() {
            writer.appendString("component")
            writer.appendString(component.name)
            writer.appendString(component.value)
        }
        writer.appendString("versions")
        writer.appendString(String(versions.count))
        for component in versions.canonicalSorted() {
            writer.appendString("component")
            writer.appendString(component.name)
            writer.appendString(component.value)
        }
        return writer.data
    }

    var stableHash: CacheKeyHash {
        CacheKeyHash(rawValue: StableDigest.sha256Hex(canonicalRepresentation))
    }
}

private extension Array where Element == CacheKeyComponent {
    func canonicalSorted() -> [CacheKeyComponent] {
        sorted { lhs, rhs in
            if lhs.name != rhs.name {
                return lhs.name < rhs.name
            }
            return lhs.value < rhs.value
        }
    }
}
